config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root to: 'homes#index'
  get '/help', to: 'homes#help'
  get '/about', to: 'homes#about'
  get '/contact', to: 'homes#contact'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
  <small>
    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
    <div class="clear"></div>
  </nav>
  </footer>
</div>

app/views/layouts/_header.html.erb
<header class="nav-wrapper">
  <div class="container">
    <div class="header-left">
      <%= link_to "Clone", root_path, id: "logo", class: "header-tag" %>
    </div>
    <div class="header-right">
      <nav>
        <li><%= link_to "Home", root_path, class: "header-tag" %></li>
        <li><%= link_to "Help", help_path, class: "header-tag" %></li>
        
        <% if logged_in? %>
          <li><%= link_to "Users", users_path, class: "header-tag" %></li>
          <li><%= link_to "Profile", user_path(current_user), class: "header-tag" %></li>
          <li><%= link_to "Settings", edit_user_path(current_user), class: "header-tag" %></li>
          <li><%= link_to "Logout", logout_path, method: :delete, class: "header-tag" %></li>
        <% else %>
          <li><%= link_to "Login", login_path, class: "header-tag" %></li>
        <% end %>
        
      </nav>
    </div>
    <div class="clear"></div>
  </div>
</header>
<div class="clear"></div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
      <%= render "layouts/header" %>
      <div class="container">
      <div class="flash-wrapper">
        <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        </div>
      </div>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    
  </body>
</html>